### ISSUE TITLE
请问clash该怎么配置

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#48]
ss用的是v2ray插件的ws+tls+web组合
请问clash该怎么配置，折腾半天没成功过

**Comment by loyess** [comment]
可以参考：https://github.com/ConnersHua/Profiles/blob/master/Clash/Global.yaml

**Comment by xidcn** [comment]
出错地方在 plugin-opts= 照抄SS参数报错

**Comment by loyess** [comment]
```
  # Shadowsocks(Websocket + TLS)
  - name: "HK"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # no QUIC now
      tls: true # wss
      # skip-cert-verify: true
      host: bing.com
      path: "/wssPath"
      mux: false
      # headers:
      #   custom: value

```
